# Generated by Django 2.1.5 on 2019-02-18 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190219_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_Date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 21, 31, 28, 577629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 21, 31, 28, 577123, tzinfo=utc)),
        ),
    ]
